version: '3'
services:
  redis: 
    image: redis:alpine
    ports:
      - "6379:6379"
  server:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
  client:
    build: ./client
    ports:
      - "3000:80"
